"""
Django settings for Diabetic project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import shlex
from urllib.parse import parse_qs
from urllib.parse import unquote
from urllib.parse import urlparse

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_DATA_DIR = os.environ.get('APP_DATA_DIR', BASE_DIR)
LOG_DIR = os.path.join(BASE_DIR, 'Diabetic', 'logs')
os.makedirs(LOG_DIR, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
debug_env = os.environ.get('DEBUG')
if debug_env is None:
    DEBUG = 'SECRET_KEY' not in os.environ
else:
    DEBUG = debug_env.lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY MUST be set via environment variable
if not DEBUG and 'SECRET_KEY' not in os.environ:
    raise ValueError('SECRET_KEY environment variable must be set in production (DEBUG=False)')
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-only-secret-key-change-in-production')

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']
render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_hostname:
    ALLOWED_HOSTS.append(render_hostname)

extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
if extra_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in extra_hosts.split(',') if host.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DiabeticApp'
]

MIDDLEWARE = [
    'DiabeticApp.middleware.error_handling.ErrorHandlingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Diabetic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Diabetic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


def _parse_kv_connection_string(connection_string):
    config = {}
    for token in shlex.split(connection_string):
        if "=" not in token:
            continue
        key, value = token.split("=", 1)
        config[key.strip().lower()] = value.strip()
    return config


def _parse_database_url(connection_string):
    parsed = urlparse(connection_string)
    query = parse_qs(parsed.query)
    return {
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or '5432'),
        'OPTIONS': {
            'sslmode': query.get('sslmode', [os.environ.get('DB_SSLMODE', 'require')])[0],
        },
    }


def _build_postgres_database(connection_string=None):
    if connection_string:
        if '://' in connection_string:
            database = _parse_database_url(connection_string)
        else:
            parsed = _parse_kv_connection_string(connection_string)
            database = {
                'NAME': parsed.get('dbname', parsed.get('database', '')),
                'USER': parsed.get('user', parsed.get('username', '')),
                'PASSWORD': parsed.get('password', ''),
                'HOST': parsed.get('host', ''),
                'PORT': parsed.get('port', '5432'),
                'OPTIONS': {
                    'sslmode': parsed.get('sslmode', os.environ.get('DB_SSLMODE', 'require')),
                },
            }
            ssl_root_cert = parsed.get('sslrootcert')
            if ssl_root_cert:
                database['OPTIONS']['sslrootcert'] = ssl_root_cert
    else:
        database = {
            'NAME': os.environ.get('AZURE_POSTGRESQL_NAME', os.environ.get('DB_NAME', '')),
            'USER': os.environ.get('AZURE_POSTGRESQL_USER', os.environ.get('DB_USER', '')),
            'PASSWORD': os.environ.get('AZURE_POSTGRESQL_PASSWORD', os.environ.get('DB_PASSWORD', '')),
            'HOST': os.environ.get('AZURE_POSTGRESQL_HOST', os.environ.get('DB_HOST', '')),
            'PORT': os.environ.get('AZURE_POSTGRESQL_PORT', os.environ.get('DB_PORT', '5432')),
            'OPTIONS': {
                'sslmode': os.environ.get('AZURE_POSTGRESQL_SSLMODE', os.environ.get('DB_SSLMODE', 'require')),
            },
        }
        ssl_root_cert = os.environ.get('AZURE_POSTGRESQL_SSLROOTCERT', os.environ.get('DB_SSLROOTCERT', ''))
        if ssl_root_cert:
            database['OPTIONS']['sslrootcert'] = ssl_root_cert

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': database['NAME'],
        'USER': database['USER'],
        'PASSWORD': database['PASSWORD'],
        'HOST': database['HOST'],
        'PORT': database['PORT'],
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        'OPTIONS': database['OPTIONS'],
    }


azure_connection_string = os.environ.get('AZURE_POSTGRESQL_CONNECTIONSTRING', '')
database_url = os.environ.get('DATABASE_URL', '')
app_service_postgres_connection = ''
for env_name, env_value in os.environ.items():
    if env_name.startswith('POSTGRESQLCONNSTR_') and env_value:
        app_service_postgres_connection = env_value
        break

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(APP_DATA_DIR, 'db.sqlite3'),
    }
}

db_engine = os.environ.get('DB_ENGINE', '').lower()
if database_url:
    DATABASES['default'] = _build_postgres_database(database_url)
elif azure_connection_string:
    DATABASES['default'] = _build_postgres_database(azure_connection_string)
elif app_service_postgres_connection:
    DATABASES['default'] = _build_postgres_database(app_service_postgres_connection)
elif db_engine in ('postgresql', 'postgres'):
    DATABASES['default'] = _build_postgres_database()


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
LOGIN_URL = 'UserLogin'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'debug.log'),
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
